name: Publish package to GitHub Packages
on:
  push:
    branches:
      - "main"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Generate settings.xml for Maven Builds
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          servers: |
            [
              {
                "id": "github",
                "username": "itaymelamed",
                "password": "${{ secrets.GITHUB_TOKEN }}"
              }
            ]
          repositories: |
            [
              {
                "id": "github",
                "url": "https://maven.pkg.github.com/itaymelamed/simple-java-maven-app",
                "snapshots": {
                  "enabled": "true"
                },
                "releases": {
                  "enabled": "true"
                }
              }
            ]
      - name: Intsall
        run: mvn -B package -s /home/runner/.m2/settings.xml --file pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USER_NAME: "itaymelamed"
